<a href="https://colab.research.google.com/github/mamoo9811/ML-Data/blob/main/Copy_of_Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
nums1 = [1, 2, 3, 0, 0, 0]
m = 3
nums2 = [2, 5, 6]
n = 3

In [ ]:
import pandas as pd

def merge(nums1, m, nums2, n):
    # ناخد بس العناصر الحقيقية من كل مصفوفة
    real_nums1 = nums1[:m]
    real_nums2 = nums2[:n]

    # ندمجهم بـ Series واحدة باستخدام pd.concat
    combined = pd.concat([pd.Series(real_nums1), pd.Series(real_nums2)])

    # نرتبها تصاعديًا
    sorted_combined = combined.sort_values()

    # نحولها لقائمة ونحطها مكان nums1
    result = sorted_combined.tolist()

    for i in range(len(result)):
        nums1[i] = result[i]

    return nums1

In [ ]:
print(merge(nums1, m, nums2, n))

[1, 2, 2, 3, 5, 6]

In [ ]:
# import pandas
import pandas as pd
# save file path
fname = "/content/drive/MyDrive/AXSOSACADEMY/01-Fundamentals/Week02/Data/Our Bake Sale [Loading Data Vers] - Day 4 Sales.csv"
df = pd.read_csv(fname)
df.head()

,Item,Student,Packaging,Price,Expense,Quantity Sold (Day 1),Quantity Sold (Day 2),Quantity Sold (Day 3),Quantity Sold (Day 4)
0,brownie,Hugo,Individually Wrapped (Plastic),2.25,0.25,17,19,25,25
1,cookie,Sally,Individually Wrapped (Plastic),1.25,0.50,40,32,38,38
2,cake,Martina,Boxed (Clear Plastic),9.50,5.00,1,2,0,0
3,cupcake,Joe,Boxed (Cardboard),3.50,0.75,10,14,12,12
4,fudge,Hugo,Individually Wrapped (Foil),3.00,1.00,0,20,22,22

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# preview the last five rows
df.tail()

,Item,Student,Packaging,Price,Expense,Quantity Sold (Day 1),Quantity Sold (Day 2),Quantity Sold (Day 3),Quantity Sold (Day 4)
7,scone,Jade,Individually Wrapped (Plastic),2.00,1.25,0,8,10,10
8,muffin,Anne,Individually Wrapped (Foil),1.50,0.75,0,3,4,4
9,rice krispies treats,Martina,Individually Wrapped (Plastic),1.25,0.25,0,0,10,30
10,apple pie,Sally,Box (Cardboard),10.00,4.00,0,0,2,3
11,key lime pie,Martina,Box (Cardboard),9.50,4.50,0,0,3,3

In [ ]:
# obtain a summary table for each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Item                   12 non-null     object
 1   Student                12 non-null     object
 2   Packaging              12 non-null     object
 3   Price                  12 non-null     float64
 4   Expense                12 non-null     float64
 5   Quantity Sold (Day 1)  12 non-null     int64
 6   Quantity Sold (Day 2)  12 non-null     int64
 7   Quantity Sold (Day 3)  12 non-null     int64
 8   Quantity Sold (Day 4)  12 non-null     int64
dtypes: float64(2), int64(4), object(3)
memory usage: 996.0+ bytes

In [ ]:
# Save the url surround by quotes
url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQNX3oBeyee-rQEulninLyZoBUy3JVUy3wsGkPRl-G-mbjh5iItwBfezeGkDHnwtxnLneBX3Ylm1c64/pub?gid=860339357&single=true&output=csv"
# Read in data from url
df_url = pd.read_csv(url)
# Preview the first five rows
df_url.head()

,Item,Student,Packaging,Price,Expense,Quantity Sold (Day 1),Quantity Sold (Day 2),Quantity Sold (Day 3),Quantity Sold (Day 4)
0,brownie,Hugo,Individually Wrapped (Plastic),2.25,0.25,17,19,25,25
1,cookie,Sally,Individually Wrapped (Plastic),1.25,0.50,40,32,38,38
2,cake,Martina,Boxed (Clear Plastic),9.50,5.00,1,2,0,0
3,cupcake,Joe,Boxed (Cardboard),3.50,0.75,10,14,12,12
4,fudge,Hugo,Individually Wrapped (Foil),3.00,1.00,0,20,22,22

In [ ]:
# Preview the last 5 rows
df_url.tail()

,Item,Student,Packaging,Price,Expense,Quantity Sold (Day 1),Quantity Sold (Day 2),Quantity Sold (Day 3),Quantity Sold (Day 4)
7,scone,Jade,Individually Wrapped (Plastic),2.00,1.25,0,8,10,10
8,muffin,Anne,Individually Wrapped (Foil),1.50,0.75,0,3,4,4
9,rice krispies treats,Martina,Individually Wrapped (Plastic),1.25,0.25,0,0,10,30
10,apple pie,Sally,Box (Cardboard),10.00,4.00,0,0,2,3
11,key lime pie,Martina,Box (Cardboard),9.50,4.50,0,0,3,3

In [ ]:
# Inspect the .info()
df_url.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Item                   12 non-null     object
 1   Student                12 non-null     object
 2   Packaging              12 non-null     object
 3   Price                  12 non-null     float64
 4   Expense                12 non-null     float64
 5   Quantity Sold (Day 1)  12 non-null     int64
 6   Quantity Sold (Day 2)  12 non-null     int64
 7   Quantity Sold (Day 3)  12 non-null     int64
 8   Quantity Sold (Day 4)  12 non-null     int64
dtypes: float64(2), int64(4), object(3)
memory usage: 996.0+ bytes